root: true

env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:lit/recommended

parser: '@typescript-eslint/parser'

parserOptions:
  project:
    - ./tsconfig.json

plugins:
  - '@typescript-eslint'

ignorePatterns:
  - dist/
  - rollup.config.js
  - src/generated/
  - tailwind.config.js
  - test/__snapshots__/

rules: {}
